import random
# un guion bajo es como un protect
# doble guion es como obligar a que sea privado y hace que no puedas acceder desde fuera "name mangling", per
# se podría acceder de otra forma: __Racional_atributo



"""
    DEBO sobreacargar todos los operadores y además 
"""
class Rational:
    def __init__(self, numerator, denominator):
        mcd = self.maxcd(numerator, denominator)
        self.numerator = numerator/mcd
        self.denominator = denominator/mcd

    def __init__(self):
        self.denominator = random.randint(-99,99)
        while self.numerator != 0:
            self.numerator = random.randint(-99, 99)



    def maxcd(self,n , d):
        if (n%d) == 0:
            return d
        return self.maxcd(n, n%d)

    def add(self, r1):
        denominator = self.denominator*r1.numerator
        numerator = denominator*r1.numerator+denominator*self.denominator
        return Rational(numerator, denominator)

    def subs(self, r1):
        denominator = self.denominator*r1.numerator
        numerator = denominator*r1.numerator-denominator*self.denominator
        return Rational(numerator, denominator)

    def multiply(self, r1):
        denominator = self.denominator*r1.denominator
        numerator = self.numerator*r1.numerator
        return Rational(denominator, numerator)
    def divide(self, r1):
        denominator = self.denominator*r1.numerator
        numerator = r1.denominator*self.numerator
        return Rational(numerator, denominator)

    def toDouble(self):
        return self.numerator / self.denominator

    def __add__(self, r1):
        return self.add(r1)

    def __sub__(self, r1):
        return self.subs(r1)

    def __mul__(self, r1):
        return self.multiply(r1)

    def __truediv__(self, r1):
        return self.divide(r1)

    def __str__(self):
        return f"{self.numerator}/{self.denominator}"


    def __eq__(self, r1):
        if not isinstance(r1, Rational):
            return NotImplemented
        return self.numerator == r1.numerator and self.denominator == r1.denominator
    #Generated by antonIA





